spring:
  application:
    name: auto-next-authentication-api


  spring:
    datasource:
      url: jdbc:postgresql://cs308-postgres.postgres.database.azure.com:5432/postgres?sslmode=require
      username: cs308user@cs308-postgres
      password: 'SvO93?2+djYd/mFy2(R7#0z'
      driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update   # ders projesi için tabloyu otomatik oluştur/güncelle
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

server:
  port: 8000

jwt:
  secret: aa8c572cd111626310a5fe513742c4561c66957a97afacddc36eed6553ad9a8c